### ISSUE TITLE
Update README.md to list data sources we're providing

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool-data#10]
We want to be clear up front what data sources are included in this repository without people having to dig, so update the README.md to list them out, currently:

 - z/OS
 - Debian 10 (Buster)
 
And write that they are updated, periodically, on a best-effort basis, with PRs welcome to add projects to z/OS (the lists for the Linux distros are generated programmatically).

**Comment by rachejazz** [comment]
Should we go ahead with this after ClefOS update?
Also, is there any 3rd party bot allowed for the regular data push? I can look up for a few

**Comment by pleia2** [comment]
Yeah, there is no rush, I was just clearing out my post-holiday issue queue 😁

**Comment by pleia2** [comment]
Once Fedora is done, we can go ahead with this :smile:
