### ISSUE TITLE
Add openSUSE data files

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool-data#13]
One for tumbleweed (rolling release) and one for leap (current version is 15.3).

We can these repositories to generate the data files:

Tumbleweed: https://download.opensuse.org/ports/zsystems/tumbleweed/

Leap 15.3: https://download.opensuse.org/distribution/leap/15.3/repo/oss/ (may have to dig around to parse just the s390x packages only, so it may not be quite as straight-forward as ClefOS was).

**Comment by rachejazz** [comment]
I'll take this up after we get a confirmation from Sine Nominie about Clef pkg :D
We need just the s390x ones or should I also count the noarch ones? Those packages mean they're supported regardless any architecture, i think we should count them

**Comment by pleia2** [comment]
Good idea on noarch 👍
