### ISSUE TITLE
Add Fedora 35

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool-data#24]
Fedora 35 was released on 2 November 2021, create a data file for it.

**Comment by rachejazz** [comment]
do you have the repo source link?

**Comment by pleia2** [comment]
https://dl.fedoraproject.org/pub/fedora-secondary/releases/35/Everything/s390x/os/Packages/

**Comment by pleia2** [comment]
As a pointer for anyone who may wish to work on this, the script that generates these source files is located in the software-discovery-tool repository: https://github.com/openmainframeproject/software-discovery-tool/blob/master/bin/package_build.py

Fedora 34 can be used as a template for working on this issue, my advice would to first update that script and submit it for review, then submit the PR for adding the new source file here.

**Comment by pleia2** [comment]
#28 solves this. Thanks @rachejazz!
