### ISSUE TITLE
Add Validated Open Source Software list as a data source

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool-data#25]
There is a Validated Open Source Software list at https://www.ibm.com/community/z/open-source-software/ that the team @cwsolee runs maintains with links to instructions they maintain for popular open source software. It would be great to get this as a data source so folks can use the SDT for finding things on the table, instead of having to use both.

**Comment by pleia2** [comment]
We now have a JSON endpoint that we can query and build our lists from: https://www.ibm.com/community/z/open-source-software/output/json/ :tada:

**Comment by pleia2** [comment]
The format is JSON, but it's not compatible with SDT, so we'll need to think about what data to include and how we want package_build.py to process it. What to include, how to display it in the UI, etc.

**Comment by rachejazz** [comment]
package_build needs a good amount of refactor. Hopefully this can be added as a todo during mentorship period

**Comment by arshPratap** [comment]
@pleia2 I have extracted information from the validated open source list and converted it into json files for our requirements you can find those files [here](https://drive.google.com/drive/folders/1wJCkBO2YnWLxQjQDvosXrIdKyTqxSixM?usp=sharing) do tell me if we need some improvements for it.
Thanks !

**Comment by pleia2** [comment]
Nice job! I loaded everything up in my development instance and it looks good.

A couple corrections with the file names:

- Ubuntu is based on Debian, but it's not Debian, so we'll want to be clear that it's instead Ubuntu 18.04 and Ubuntu 20.04 (not Debian Buster and Bullseye). And it's not openSUSE 15, it's SUSE Linux Enterprise Server 15 (short name is SLES 15).
- And I think the file names should instead be like: IBM_Validated_OSS_List_Ubuntu_1804.json and IBM_Validated_OSS_List_SLES_15.json (leading with what it is makes them easy to identify in the alphabetized lists)

**Comment by pleia2** [comment]
@arshPratap I think the last component of this would be taking https://github.com/arshPratap/SDT-Validated-Open-Source-List/blob/main/Validated_OpenSource.ipynb and crafting it into a script that we can include in the software-discovery-tool project. I will create a separate issue for that in that repository though.
