### ISSUE TITLE
Add IBM Z and LinuxONE Container Image Registry as data source

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool-data#26]
The IBM Z and LinuxONE Container Image Registry (https://ibm.github.io/ibm-z-oss-hub/containers/index.html) would make another good data source. Sync up with @jabostian and team in 2022 to figure out the best way to regularly pull the information into a JSON data file.

**Comment by rachejazz** [comment]
This is great!! So do i need to make it a separate datafile or could we replace the Z/OS data file with this?

**Comment by pleia2** [comment]
While this runs on z/OS, the containers in zCX are still Linux, so we'll want this to be a separate data file specifically for s390x container images in this registry 👍

**Comment by rachejazz** [comment]
Another question, what should be done with pkgs with multiple versions? Will take this to our next meeting 👍

**Comment by pleia2** [comment]
That's a very good question. My inclination is to add each version as a different entry in the JSON file, but discussion at the next meeting would be good since we can also loop @jabostian in to get his thoughts.

**Comment by pleia2** [comment]
Solved by the linked PR from @korpx-z :tada:
