### ISSUE TITLE
Debian Source Link

### ISSUE THREAD

**Issue by rachejazz** [openmainframeproject/software-discovery-tool-data#27]
Today I have tried renewing the data files and looks like ftp.debian.org has been stopped:
![image](https://user-images.githubusercontent.com/42383989/148804768-953b07b0-e455-4e50-ac26-19502d0942b1.png)

Following screenshot supports it:
![image](https://user-images.githubusercontent.com/42383989/148804839-417e0f78-6de3-43f2-bac3-61a0a3a81b96.png)

**Comment by pleia2** [comment]
Figured it out, 10.10 is no more! We'll need to update the file with the Debian10.11 source directory. I'll create a PR over in the SDT project and add you as a reviewer.

**Comment by pleia2** [comment]
https://github.com/openmainframeproject/software-discovery-tool/pull/77
