### ISSUE TITLE
Remove IBM_Validated_OSS_List_Ubuntu_1804.json 

### ISSUE THREAD

**Issue by Princee215** [openmainframeproject/software-discovery-tool-data#55]
As seen recently, in the live list https://www.ibm.com/community/z/open-source-software/ for **IBM validated open source software Ubuntu 18.04** is removed as it is no longer supported. 

Therefore, we might need to remove it from our data files too. As of now creating a file for it through ./bin/package_build.py would result in an empty file. We also have to comment it out from our supported distros file in our core repo. @pleia2, @arshPratap Please take a look and let me know if there's anything else that I could add here.

**Comment by pleia2** [comment]
Agreed, we should only be shipping 20.04 and 22.04 sources for this now that the source has dropped 18.04.

**Comment by Princee215** [comment]
Yup. I've made the required changes in my PR too. As of now, only IBM_Validated_OSS_List_Ubuntu_2004.json and IBM_Validated_OSS_List_Ubuntu_2204.json files could be created through it.
