### ISSUE TITLE
Remove characters not in ASCII range 

### ISSUE THREAD

**Issue by indranilm256** [openmainframeproject/software-discovery-tool-data#7]
When formatting the spreadsheet to json, some characters were replaced by replacement character(�). This may have happened due to conversion from Unicode to ASCII in which case some punctuation marks couldn't be recognized or approximated to their ASCII equivalents.

**Comment by rachejazz** [comment]
Have you been able to do it? There's a very basic command line fu to do this.

**Comment by indranilm256** [comment]
Yes there were only 6 occurrences of that, so I did it manually. Thanks for the idea though fu seems like a great command to use

**Comment by rachejazz** [comment]
"fu" isn't a command😅 just a figure of speech you use similar to "kungfu"
But that's great if the issue is solved. Maybe we can add a filter from next time while converting. Can't expect to do this manually everytime imo

**Comment by rachejazz** [comment]
can you tell me which places btw? I am still getting this:
```
[Wed Jun 23 08:54:55.479115 2021] [wsgi:error] [pid 5699:tid 140663570355968] [remote 172.16.50.1:33900]   File "/opt/software-discovery-tool/src/classes/package_search.py", line 79, in preparePackageData
[Wed Jun 23 08:54:55.479121 2021] [wsgi:error] [pid 5699:tid 140663570355968] [remote 172.16.50.1:33900]     package_info = json.load(open('%s/%s' % (data_dir, distro_file)))
[Wed Jun 23 08:54:55.479131 2021] [wsgi:error] [pid 5699:tid 140663570355968] [remote 172.16.50.1:33900]   File "/usr/lib/python3.8/json/__init__.py", line 293, in load
[Wed Jun 23 08:54:55.479137 2021] [wsgi:error] [pid 5699:tid 140663570355968] [remote 172.16.50.1:33900]     return loads(fp.read(),
[Wed Jun 23 08:54:55.479147 2021] [wsgi:error] [pid 5699:tid 140663570355968] [remote 172.16.50.1:33900]   File "/usr/lib/python3.8/encodings/ascii.py", line 26, in decode
[Wed Jun 23 08:54:55.479153 2021] [wsgi:error] [pid 5699:tid 140663570355968] [remote 172.16.50.1:33900]     return codecs.ascii_decode(input, self.errors)[0]
[Wed Jun 23 08:54:55.479192 2021] [wsgi:error] [pid 5699:tid 140663570355968] [remote 172.16.50.1:33900] UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 9615: ordinal not in range(128)
```

**Comment by indranilm256** [comment]
Sorry about that. I'll make PR. You can search and replace the occurrences of this character "�".
